/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "add.h"

bool_t
xdr_add_in (XDR *xdrs, add_in *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->a))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->b))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_add_out (XDR *xdrs, add_out *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->sum))
		 return FALSE;
	return TRUE;
}
