
all : fielder bowl umpire bat

fielder : fielder.c
	gcc -o fielder.exe fielder.c

bowl : bowl.c
	gcc -o bowl.exe bowl.c

umpire : umpire.c
	gcc -o umpire.exe umpire.c

bat : bat.c
	gcc -o bat.exe bat.c