
all : DS D1 D2 D3 D4 C

DS: DS.c
	gcc -o DS.exe DS.c

D1: D1.c
	gcc -o D1.exe D1.c

D2: D2.c
	gcc -o D2.exe D2.c

D3: D3.c
	gcc -o D3.exe D3.c

D4: D4.c
	gcc -o D4.exe D4.c

C: C.c
	gcc -o C.exe C.c


gcc D1.c -o D1.exe
gcc D2.c -o D2.exe
gcc D3.c -o D3.exe
gcc D4.c -o D4.exe
gcc C.c -o C.exe
gcc DS.c -o DS.exe

