all : b d c w1 w2 w3

b : b.cpp
	g++ b.cpp -g -lACE -o b.exe

d : d.cpp
	g++ d.cpp -g -lACE -o d.exe

c : c.cpp
	g++ c.cpp -g -lACE -o c.exe

w1 : w1.cpp
	g++ w1.cpp -g -lACE  -o w1.exe

w2 : w2.cpp
	g++ w2.cpp -g -lACE  -o w2.exe

w3 : w3.cpp
	g++ w3.cpp -g -lACE  -o w3.exe

